version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    container_name: db
    ports:
      - "127.0.0.1:3901:3306"
    environment:
      MYSQL_ROOT_PASSWORD: localHost
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
